// Run once with: node scripts/generate-icons.mjs
// Produces public/icons/*.png from hand-authored SVG source (no external
// assets, no Next.js/Vercel default icons).
import sharp from "sharp";
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(__dirname, "..", "public", "icons");
mkdirSync(outDir, { recursive: true });

const ROSE_BG = "#B76E79";
const ROSE_DARK = "#8F4F5A";
const CHEEK = "#8F4F5A";
const BODY_LIGHT = "#F3D9DE";

/**
 * A simplified, bold version of the SNEK snake mascot, drawn edge-to-edge
 * on a solid dusty-rose background so it reads clearly at small sizes.
 * `padding` (0-1) shrinks/centers the character to leave safe-zone margin
 * for maskable icons.
 */
function makeIconSvg({ size, padding = 0, background = true }) {
  const inset = size * padding;
  const inner = size - inset * 2;

  return `
<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg">
  ${background ? `<rect width="${size}" height="${size}" fill="${ROSE_BG}"/>` : ""}
  <g transform="translate(${inset}, ${inset})">
    <svg width="${inner}" height="${inner}" viewBox="0 0 120 120">
      <defs>
        <linearGradient id="body" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="${BODY_LIGHT}"/>
          <stop offset="100%" stop-color="#FFFFFF" stop-opacity="0.92"/>
        </linearGradient>
      </defs>
      <!-- tail -->
      <path d="M18 96c-6-10-2-24 10-28 9-3 17 3 16 12-1 7-8 10-13 6"
        fill="none" stroke="url(#body)" stroke-width="16" stroke-linecap="round"/>
      <!-- body -->
      <path d="M22 90 C10 60 20 30 46 20 C72 10 100 26 100 52"
        fill="none" stroke="url(#body)" stroke-width="24" stroke-linecap="round"/>
      <!-- head -->
      <circle cx="86" cy="46" r="30" fill="url(#body)"/>
      <circle cx="75" cy="55" r="7" fill="${CHEEK}" opacity="0.35"/>
      <circle cx="98" cy="55" r="7" fill="${CHEEK}" opacity="0.35"/>
      <!-- happy eyes -->
      <path d="M73 40 Q78 33 83 40" stroke="${ROSE_DARK}" stroke-width="4.5" fill="none" stroke-linecap="round"/>
      <path d="M90 40 Q95 33 100 40" stroke="${ROSE_DARK}" stroke-width="4.5" fill="none" stroke-linecap="round"/>
      <path d="M75 58 Q86 70 97 58" stroke="${ROSE_DARK}" stroke-width="5" fill="none" stroke-linecap="round"/>
    </svg>
  </g>
</svg>`;
}

async function render(name, size, opts) {
  const svg = makeIconSvg({ size, ...opts });
  await sharp(Buffer.from(svg)).png().toFile(path.join(outDir, name));
  console.log("wrote", name, size);
}

async function main() {
  await render("icon-192.png", 192, { padding: 0 });
  await render("icon-512.png", 512, { padding: 0 });
  // Maskable: OS may crop up to ~20% from each edge, so keep the character
  // inside a ~68% safe zone while the background still fills the canvas.
  await render("icon-512-maskable.png", 512, { padding: 0.16 });
  await render("apple-touch-icon.png", 180, { padding: 0 });
  // Also drop a plain favicon-sized PNG for browser tabs.
  await render("favicon-32.png", 32, { padding: 0 });
  await render("favicon-16.png", 16, { padding: 0 });

  writeFileSync(
    path.join(outDir, "README.txt"),
    "Generated by scripts/generate-icons.mjs. Re-run that script if the brand mascot/colors change.\n"
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
